---
title: "A Very Large Expanse of Sea"
output: html_document
---
Mafi, T. (2018). A Very Large Expanse of Sea. HarperCollins.

In A Very Large Expanse of Sea, Shirin is a headstrong, cool hijabi starting her sophomore year at a new high school. It is the year after 9/11 and for Shirin, who has dealt with bigotry all her life, routine verbal abuse from her peers is all too familiar. Over the course of the school year, Shirin matures in surprising ways. She fulfills a lifelong dream of learning to breakdance and stars in a breakdancing crew. She also has her first relationship with the school’s golden boy, Ocean, which causes some turbulence in Shrin’s life and the community. 

I thoroughly enjoyed A Very Large Expanse of Sea and would definitely recommend it to anyone who likes Coming of Age novels. Shirin is a great character: she is effortlessly cool, likable, and has unique interests that I feel are underrepresented in media. I honestly aspire to have her self-confidence, especially given her age. I also found myself giddily listening to the progression of the relationship between Shirin and Ocean. The ideas explored in the novel, like stereotyping and bigotry, remind us to be non-judgemental in our interactions with others. Also, we see how Shirin’s world changes when she lets her guard down, showing us how elation and disappointment are all part of the human experience. This story is not all sunshine and rainbows and succeeds in its honest depiction of teen life.   
