---
title: "Hello, Goodbye, and Everything in Between"
output: html_document
---
Lewen, M. (Director). (2022). Hello, Goodbye, and Everything in Between [Film]. ACE Entertainment; Lionsgate.

Claire is leaving for Dartmouth College in the morning so she scheduled her breakup with Aidan tonight. Don’t worry, they’ve been planning this breakup ever since they got together last summer. Who wants to start college with the baggage of their high school relationship weighing them down? Aidan plans a night of relieving their firsts, including their first date, first hockey game, and first Valentine’s. As the night winds to an end, Claire and Aidan are left wondering if leaving their relationship behind is really the right decision.

I don’t think anyone needs to go out of their way to see this movie. Unless, of course, you’re a fan of rising star Ayo Edebiri, who delivers an amazing performance as Stella, Claire’s BFF. The premise of this movie is interesting, but the storyline is pretty predictable. For me, this film’s portrayal of high school and teen relationships was too romanticized. Which is a lot coming from me because I love nothing more than a teenage hijinks movie, particularly when the hijinks happen all in one night. I think I prefer over-the-top teen movies where a friendship is central to the plot, not a romantic relationship. As an alternative to Hello, Goodbye, and Everything in Between, I would recommend Booksmart, which has the same carefree, last-night-before-the-rest-of-our-lives energy. 
