---
output: 
  html_document:
    includes:
      in_header: sidenav.html
---

<!-- Page content -->
<div class="main">
<div class="card">
# The absolutely true diary of a part-time Indian
### Date
Alexie, S. (2007). The absolutely true diary of a part-time Indian. Little, Brown and Company.

The Absolutely True Diary of a Part-Time Indian follows Junior who, like generations before him, was born and raised on the Spokane Indian Reservation. Over time, Junior begins to want something different for his life. He starts attending a new school where he is the only Native American student. Over the course of the school year, Junior experiences tragedy and struggles with his identity. Will Junior ever learn to embrace his status as a ‘part-time’ Indian?

I really enjoyed this semi-autobiographical novel by Sherman Alexie. Junior’s internal struggles are relatable to anyone who has felt like the black sheep in their family or neighborhood. Due to themes of drug use and violence, this The Absolutely True Diary of a Part-Time Indian has been frequently banned in the United States. While this story was widely-awarded when it was published, over time its critical acclaim has been retracted due to allegations of sexual misconduct by Alexie. Personally, after learning about this misconduct, I felt myself deflate and my appreciation for the book diminish. For anyone who reads this book, I would encourage you to question the merit of the art versus the artist and to honor whatever feelings bubble up for you.

</div>
</div>
