---
title: "The Hate U Give"
output: html_document
---
Thomas, A. (2018). The hate u give. Walker Books.

Starr’s life has always been complicated: split between the cultures of her home neighborhood, Garden Heights, and the school she attends, Williamson Prep. When she experiences first-hand the trauma of best friend’s murder at the hands of the police, her life changes forever. Starr must confront everyday microaggressions in her life systemic racism. Above all, Starr must gain the confidence to use her voice to speak out for herself and what she believes is right. 

The Hate U Give is rightfully, widely praised. Angie Thomas an excellent writer, developing engaging characters and enthralling story, and also speaking to critical issues in our society today. This book provides a multidimensional, personal perspective to narratives that are often flattened in the media. I think this book should be required reading in classrooms everywhere. For Black teens, The Hate U Give provides a chance to feel seen and for everyone else, it provides a course on empathy. I am excited to dive into the rest of Thomas’ novels and watch The Hate U Give film adaptation. 
